// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechStore.Data;

#nullable disable

namespace TechStore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechStore.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Laptops y PCs para el día a día.",
                            Nombre = "Computadoras"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Smartphones de las mejores marcas.",
                            Nombre = "Celulares"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Mouse, teclados, audífonos y más.",
                            Nombre = "Accesorios"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Todo lo que necesitás para jugar.",
                            Nombre = "Gaming"
                        });
                });

            modelBuilder.Entity("TechStore.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descripcion = "Laptop ligera con pantalla de 14 pulgadas.",
                            Estado = true,
                            Imagen = "/images/laptop1.png",
                            Nombre = "Mackbook Air",
                            Precio = 899.00m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            Descripcion = "Smartphone con cámara nítida y batería duradera.",
                            Estado = true,
                            Imagen = "/images/telefono1.png",
                            Nombre = "Iphone 17",
                            Precio = 649.00m,
                            Stock = 14
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 3,
                            Descripcion = "Audífonos inalámbricos con sonido envolvente.",
                            Estado = true,
                            Imagen = "/images/audifono1.png",
                            Nombre = "Sony WH-1000XM4",
                            Precio = 129.00m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 4,
                            Descripcion = "Control ergonómico para tus sesiones de juego.",
                            Estado = true,
                            Imagen = "/images/control1.png",
                            Nombre = "Ps5 Dualsense",
                            Precio = 79.00m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 1,
                            Descripcion = "Monitor Full HD de 27 pulgadas y 120 Hz.",
                            Estado = true,
                            Imagen = "/images/monitor1.png",
                            Nombre = "Monitor 4K",
                            Precio = 269.00m,
                            Stock = 7
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 3,
                            Descripcion = "Reloj inteligente para tu ritmo diario.",
                            Estado = false,
                            Imagen = "/images/reloj1.png",
                            Nombre = "Apple Watch",
                            Precio = 159.00m,
                            Stock = 0
                        });
                });

            modelBuilder.Entity("TechStore.Models.Producto", b =>
                {
                    b.HasOne("TechStore.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("TechStore.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
